### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by duke79** [ExJarvis/ExJarvis#17]
* [ ] Backend driven search (optional?)
* [ ] Darker borders and background (dark mode?)
* [ ] Transparency
* [ ] Faster auto navigation using react hook and moment, instead of timeout (useSpring?)
* [ ] Scroll bar style

### Child issues:

- [ ] Scroll into view not working #11
